name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2.3.0
        with:
          distribution: temurin
          java-version: 16
          cache: gradle
      - name: Configure Git user details
        run: git config --global user.email "actions@github.com" && git config --global user.name "Github Actions"
      - name: Apply patches
        run: ./gradlew applyPatches
      - name: Paperclippin
        run: ./gradlew paperclipJar
      - name: artifact
        uses: actions/upload-artifact@v2
        with:
          name: Fiadelity
          path: build/libs/Fiadelity-1.17.1-R0.1-SNAPSHOT.jar
      - name: Prepare Github Page Files
        run: |
          mkdir -p public
          cp build/libs/Fiadelity-1.17.1-R0.1-SNAPSHOT.jar public/
      - name: Deploy to Github Pages
        if: github.event_name != 'pull_request'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: releases/1.17.1
