name: blak-smok
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '-g')"
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2.3.0
        with:
          distribution: temurin
          java-version: 16
          cache: gradle
      - name: Configure Git User Details
        run: git config --global user.email "actions@github.com" && git config --global user.name "Github Actions"
      - name: Apply Patches
        run: ./gradlew applyPatches --stacktrace
      - name: the typical tar
        run: tar -czf c.tar.gz Fiadelity-*
      - name: artifact xd
        uses: actions/upload-artifact@v2
        with:
          name: blak-smok
          path: c.tar.gz
